# Generated by Django 3.1.5 on 2021-01-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
