# Generated by Django 3.1.5 on 2021-01-30 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodnik', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageViews',
            new_name='PageView',
        ),
    ]
